#!/bin/sh
eval "$(xresvars)"

# WM-specific options
[ "$wm" ] || {
	id=$(xprop -root -notype _NET_SUPPORTING_WM_CHECK)
	id=${id##* }
	wm=$(xprop -id "$id" -notype _NET_WM_NAME)
	wm=${wm#*\"}
	wm=${wm%\"*}
}

border_width=1
case $wm in
	bspwm)
		_() bspc config "$@"
		for i in top bottom left right; do _ ${i}_padding 0; done
		_ window_gap 
		_ border_width 
		_ normal_border_color "$bg2"
		_ focused_border_color "$foreground"
	;;

	berry)
		_() berryc "$@"

		_ title_height 24
		_ draw_text false
		_ set_font "$fn"
		_ text_focus_color "$foreground"
		_ text_unfocus_color "$fg2"

		_ border_width 0
		_ inner_border_width 0
		_ focus_color "$ab"
		_ unfocus_color "$background"
		_ inner_focus_color "$ac"
		_ inner_unfocus_color "$background"
	;;

	herbstluftwm)
		_() herbstclient attr "$@"

		_ theme.title_height 0
		_ theme.title_color "$background"
		_ theme.title_font "$fn:pixelsize=$fs"

		_ theme.border_width "$(( border_width * 2 ))"
		_ theme.inner_width "$border_width"
		_ theme.color '#ffffff'
		_ theme.normal.inner_color "$bg2"
		_ theme.active.inner_color "$foreground"
	;;
esac

# Wallpaper
. "$XDG_CONFIG_HOME/user-dirs.dirs"
xwallpaper --stretch "$XDG_PICTURES_DIR/wal/light/1635775108030.png"
xsetroot -solid "$bg2"
