#!/bin/sh
# WM specific options
bspc config border_width 2
bspc config normal_border_color "#000000"
bspc config focused_border_color "#e0e0e0"

# Wallpaper
. "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs"
xwallpaper --stretch "$XDG_PICTURES_DIR/wal/dark/bg.jpg"

# etc.
sed -i 's/mountaineer-light/mountaineer/' "$vim"
sed -i 's/dark-mode", false/dark-mode", true/' "$ujs"
sed -i 's/DarkTheme", 0/DarkTheme", 1/' "$ujs"
