#!/bin/sh
eval "$(xrescolors)"

# WM-specific options
[ "$wm" ] || {
	id=$(xprop -root -notype _NET_SUPPORTING_WM_CHECK)
	id=${id##* }
	wm=$(xprop -id "$id" -notype _NET_WM_NAME)
	wm=${wm#*\"}
	wm=${wm%\"*}
}

case $wm in
	bspwm)
		_() bspc config "$@"
		for i in top bottom left right; do _ ${i}_padding 0; done
		_ window_gap 0
		_ border_width 0
		_ normal_border_color ""
		_ focused_border_color ""
	;;

	berry)
		_() berryc "$@"

		_ title_height 24
		_ draw_text false
		_ set_font "$fn"
		_ text_focus_color "$foreground"
		_ text_unfocus_color "$fg2"

		_ border_width 0
		_ inner_border_width 0
		_ focus_color "$ab"
		_ unfocus_color "$background"
		_ inner_focus_color "$ac"
		_ inner_unfocus_color "$background"
	;;

	herbstluftwm)
		_() herbstclient attr "$@"

		_ theme.title_height 0
		_ theme.title_color ""
		_ theme.title_font ""

		_ theme.border_width 0
		_ theme.inner_width 0
		_ theme.color ""
		_ theme.normal.inner_color ""
		_ theme.active.inner_color ""
	;;
esac

# Wallpaper
. "$XDG_CONFIG_HOME/user-dirs.dirs"
xwallpaper --zoom "$XDG_PICTURES_DIR/Wallpapers/wp.png"
xsetroot -solid "$background"
