#!/bin/sh

hc() herbstclient "$@"
hc emit_hook reload

# Theme
hc attr theme.reset 1
theme "$theme"
eval "$(xresvars)"

# Workspaces
hc rename default 1
for i in 1 2 3 4 5 6 7 8 9; do
	hc add "$i"
done

# Keybindings
hc keyunbind --all
Mod=Mod4 # alt, super=4

# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right

# splitting frames
# create an empty frame at the specified direction
splitstep=0.5
hc keybind $Mod-u split left 0.75
hc keybind $Mod-o split right 0.75
hc keybind $Mod+Control+Shift+Left split left 0.5
hc keybind $Mod+Control+Shift+Down split down 0.5
hc keybind $Mod+Control+Shift+Up split up 0.5
hc keybind $Mod+Control+Shift+Right split right 0.5
hc keybind $Mod-Control-space split explode
hc split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-comma pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space \
	or , and . compare tags.focus.curframe_wcount = 2 \
	. cycle_layout +1 vertical horizontal max vertical grid \
	, cycle_layout +1

# focus
hc keybind $Mod-Tab         cycle_all +1

# Mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# Settings
hc set frame_gap "$internalBorder"
hc set frame_padding 0
hc set frame_border_width 0
hc set frame_active_opacity 0
hc set frame_bg_transparent on
hc set default_frame_layout vertical
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set snap_gap "$internalBorder"
hc set snap_distance 25
hc set mouse_recenter_gap 0
hc set focus_follows_mouse on

# Rules
hc unrule -F
hc floating
hc rule focus=on
hc rule floatplacement=smart
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP|UTILITY)' manage=off
rules

hc set tree_style '╾│ ├└╼─┐'

hc unlock
