#!/bin/sh
# WM specific options
bspc config border_width 2
bspc config normal_border_color "#e0e0e0"
bspc config focused_border_color "#252525"

# Wallpaper
. "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs"
xwallpaper --stretch "$XDG_PICTURES_DIR/bg2.jpg"

# etc.
sed -i 's/mountaineer.*/mountaineer-light/' "$vim"
sed -i 's/dark-mode", true/dark-mode", false/' "$ujs"
sed -i 's/DarkTheme", 1/DarkTheme", 0/' "$ujs"
