#!/bin/sh
# WM specific options
bspc config border_width 2
bspc config normal_border_color "#e0e0e0"
bspc config focused_border_color "#252525"

# Wallpaper
xwallpaper --stretch "$HOME/Themes/light-pink-flat/ffe5fa.png"

# etc.
sed -i 's/mountaineer.*/mountaineer-light/' "$vim"
sed -i 's/dark-mode", true/dark-mode", false/' "$ujs"
sed -i 's/DarkTheme", 1/DarkTheme", 0/' "$ujs"
