#!/bin/sh
eval "$(xresvars)"

# WM-specific options
[ "$wm" ] || {
	id=$(xprop -root -notype _NET_SUPPORTING_WM_CHECK)
	id=${id##* }
	wm=$(xprop -id "$id" -notype _NET_WM_NAME)
	wm=${wm#*\"}
	wm=${wm%\"*}
}

border_width=12
case $wm in
	bspwm)
		_() bspc config "$@"

		for i in top bottom left right; do _ ${i}_padding 0; done
		_ window_gap 12
		_ border_width "$(( border_width * 2 ))"
		_ normal_border_color "$background"
		_ focused_border_color "$foreground"
		killall -q borders; "${bspwm%/*}/borders" &
	;;

	berry)
		_() berryc "$@"

		_ title_height 0
		_ draw_text false
		_ set_font "$fn-$fs"
		_ text_focus_color "${foreground#?}"
		_ text_unfocus_color "${fg2#?}"

		_ border_width 12
		_ inner_border_width 12
		_ focus_color "${background#?}"
		_ unfocus_color "${background#?}"
		_ inner_focus_color "${ab#?}"
		_ inner_unfocus_color "${bg2#?}"
	;;

	herbstluftwm)
		_() herbstclient attr "$@"

		_ theme.title_height 0
		_ theme.title_color "$background"
		_ theme.title_font "$fn:pixelsize=$fs"

		_ theme.border_width "$(( border_width * 2 ))"
		_ theme.inner_width "$border_width"
		_ theme.color "$background"
		_ theme.normal.inner_color "$bg2"
		_ theme.active.inner_color "$foreground"
	;;
esac

# Wallpaper
. "$XDG_CONFIG_HOME/user-dirs.dirs"
xwallpaper --zoom "$XDG_PICTURES_DIR/wal/unsplash/dark/photo-1502057524896-ffd356c88f8d.jpg"
xsetroot -solid "$bg2"

# etc.
sed -i 's/dark-mode", false/dark-mode", true/' "$ujs"
sed -i 's/DarkTheme", 0/DarkTheme", 1/' "$ujs"
